language: python
python:
    - "2.7"
install: "pip install -r requirements.txt"
script: nosetests
notifications:
    webhooks:
        urls:
            - https://dev-hooks.img.tl/travis
        on_success: always
        on_failure: always
        on_start: true
