language: python
python:
    - "2.7"
before_install:
    - echo 'yes' | sudo add-apt-repository ppa:chris-lea/node.js
    - sudo apt-get update
    - sudo apt-get install -y nodejs
install:
    - sudo npm install -g jshint
    - pip install -r requirements.txt
before_script: mkdir -p uploads/thumb
script:
    - jshint --verbose static/js
    - nosetests
after_script: rm -r uploads
notifications:
    webhooks:
        urls:
            - https://dev-hooks.img.tl/travis
        on_success: always
        on_failure: always
        on_start: always
