language: python
python:
    - "2.7"
before_install:
    - echo 'yes' | sudo add-apt-repository ppa:chris-lea/node.js
    - sudo apt-get update
    - sudo apt-get install -y nodejs ruby1.9.1
install:
    - gem install scss-lint
    - sudo npm install -g jshint
    - pip install flake8
    - pip install -r requirements.txt
before_script: mkdir -p uploads/thumb
script:
    - scss-lint static/scss
    - jshint --verbose static/js
    - flake8 --ignore=E124,E128,E302,E501 .
    - nosetests
after_script: rm -r uploads
notifications:
    webhooks:
        urls:
            - https://dev-hooks.img.tl/travis
        on_success: always
        on_failure: always
        on_start: always
